### ISSUE TITLE
send() function not working

### ISSUE THREAD

**Issue by Yetiowner** [lukespademan/microbitdongle#1]
This is my code:
mb.send("display.scroll('asdf')")
it is not sending it to my microbit! How can I fix this?

**Comment by mokytis** [comment]
Does `mb.recv()` work for you?

**Comment by Yetiowner** [comment]
yes, mb.recv() works fine, and I use it often for debuging!

**Comment by Yetiowner** [comment]
I just cannot get `mb.send` to execute code on the microbit!

**Comment by Yetiowner** [comment]
Never mind! I have got it working! TY for awesome module!

**Comment by PTaylour** [comment]
@Yetiowner I can send and receives lines on the microbit. Did you have to do anything special on the microbit for the example you mentioned to work?

> `mb.send("display.scroll('asdf')")`

**Comment by mokytis** [comment]
Have you flashed your micro:bit with a copy of micropython (i.e. have you ever ran a python program on your micro:bit)?

**Comment by PTaylour** [comment]
hi @mokytis thanks for taking the time to reply :)

I have run another python program on the microbit, yep.

At the moment I'm running `microbitdongle` on a pi and writing the name of an icon to the serial port.

Then, using python on the microbit, I'm looking up an `Image` and displaying it.

```
while True:
    sleep(500)
    try:
        bytestring = uart.readline()
        icon = weather[str(bytestring, 'utf-8')]
        display.show(icon)
    except Exception:
        pass
```

This works great.

I was looking at whether there was an easy way to do more for the logic on the pi. Like in the example `mb.send("display.scroll('asdf')")`.
